// import { env } from '@/env.mjs';

export const siteConfig = {
  name: 'Sayan Senapati',
  title: 'Sayan Senapati | Full-Stack developer',
  email: 'sayansenapati2544@gmail.com',
  description:
    "Hello, I'm Sayan. I am full-stack web developer from india. I enjoy building sites, web apps and saas applications. My focus is React (Next.js).",
  keywords: [
    'Sayan Senapati',
    'Full-Stack developer',
    'Indian developer',
    'Portfolio',
    'Software engineer',
    'Web developer',
    'Full-Stack',
    'Full-Stack development',
    'Software development',
    'Software engineer',
    'Programming',
    'Coding',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'Express.js',
    'MongoDB',
    'PostgreSQL',
    'SQL',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Bootstrap',
    'React',
    'Next.js',
    'Web development',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
  url: 'https://sayan4.vercel.app',
  // googleSiteVerificationId: env.GOOGLE_SITE_VERIFICATION_ID || '',
  links: {
    github: 'https://www.github.com/senapati484',
    linkedin: 'https://www.linkedin.com/in/sayan-senapati-430833211/',
    twitter: 'https://x.com/SayanSenapati11',
    linktree: 'https://linktr.ee/Sayan_senapati',
    instagram: 'https://www.instagram.com/sayan_senapati_',
    facebook: 'https://www.facebook.com/share/PMeACd8YPrEx31Mk',
    youtube: 'https://www.youtube.com/@sayansenapati1',
    whatsapp: 'https://wa.me/918277777777',
  },
};
